install python attrdict module during salt provisioning - required for custom salt modules extension modules - fix loading / virtual when attrdict not available template for writing base64 to file (avoid binary data in pillar) temporary fixes for epel zchunk issue uuids fix yum repos clean up duplicated IP address values by using variable expansion cosmetic package missing from broken epel repo pxeboot image path fix role reorg - for ipa server http service to work around EPEL repo bug (zchunk incompatibility) private layer ipa fixes. deployment / diagnostics improvements reactivate gitlab stuff and work on gitlab runner firewall common reject-and-log chain simple http service to work around epel bug timezone support more generic diagnostics support using pillar add bundled pkgs dir for pypi packages Gitlab runner and mattermost integration cleanup fixes use nfs4 during kickstart install more minimal roles and package sets, to reduce install time while testing - get rid of gnome and kde desktop use salt-secret for grafana fixes minor cleanup

diff --git a/salt/state/scripts/salt-render b/salt/state/scripts/salt-render
--- a/salt/state/scripts/salt-render
+++ b/salt/state/scripts/salt-render
@@ -1,6 +1,13 @@
 #!/bin/bash
 prefix="/soestack/salt/state/"
-name="${1//./\/}"
+
+if [[ ! -d "${prefix}" ]]
+then
+    echo "ERROR: Please run on the salt master" 1>&2
+    exit 1
+fi 
+
+name="${1//.//}"
 path="${prefix}/${name}"
 main_sls="${path}.sls"
 init_sls="${path}/init.sls"
